name: charts_common_maintained
version: 0.12.1
description: A common library for charting packages.
homepage: https://github.com/OttomanDeveloper/google_charts

environment:
  sdk: ">=2.18.0 <=4.0.0"

dependencies:
  collection: ^1.17.0
  intl: ^0.18.0
  logging: ^1.1.1
  meta: ^1.9.1
  vector_math: ^2.1.4

dev_dependencies:
  mockito: ^5.4.0
  test: ^1.21.4
