name: charts_flutter
version: 0.12.1
description: Material Design charting library for flutter.
homepage: https://github.com/OttomanDeveloper/google_charts

environment:
  sdk: ">=2.18.0 <=4.0.0"
#  flutter: '>=2.5.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  charts_common:
    git:
      url: https://github.com/OttomanDeveloper/google_charts.git
      ref: master
      path: charts_common
  collection: ^1.17.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.1.1
  meta: ^1.9.1

dev_dependencies:
  mockito: ^5.4.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  test: ^1.21.4
